# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-slave-pv
#   labels:
#     type: local
# spec:
#   storageClassName: jenkins-gp2
#   capacity:
#     storage: 30Gi
#   accessModes:
#     - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-slave-pvc
  namespace: jenkins
spec:
  storageClassName: jenkins-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi