apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-gp2
  namespace: jenkins
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4